/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkMonitoringRouteImport } from './routes/_app/work-monitoring'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppLiveFeedsRouteImport } from './routes/_app/live-feeds'
import { Route as AppIncidentsRouteImport } from './routes/_app/incidents'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCrowdManagementRouteImport } from './routes/_app/crowd-management'
import { Route as AppCamerasRouteImport } from './routes/_app/cameras'
import { Route as AppAuditLogsRouteImport } from './routes/_app/audit-logs'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings.notifications'
import { Route as AppLiveFeedsIdRouteImport } from './routes/_app/live-feeds.$id'
import { Route as AppIncidentsIdRouteImport } from './routes/_app/incidents.$id'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkMonitoringRoute = AppWorkMonitoringRouteImport.update({
  id: '/work-monitoring',
  path: '/work-monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveFeedsRoute = AppLiveFeedsRouteImport.update({
  id: '/live-feeds',
  path: '/live-feeds',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrowdManagementRoute = AppCrowdManagementRouteImport.update({
  id: '/crowd-management',
  path: '/crowd-management',
  getParentRoute: () => AppRoute,
} as any)
const AppCamerasRoute = AppCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppLiveFeedsIdRoute = AppLiveFeedsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLiveFeedsRoute,
} as any)
const AppIncidentsIdRoute = AppIncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIncidentsRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/cameras': typeof AppCamerasRoute
  '/crowd-management': typeof AppCrowdManagementRoute
  '/dashboard': typeof AppDashboardRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/live-feeds': typeof AppLiveFeedsRouteWithChildren
  '/users': typeof AppUsersRoute
  '/work-monitoring': typeof AppWorkMonitoringRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/live-feeds/$id': typeof AppLiveFeedsIdRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/cameras': typeof AppCamerasRoute
  '/crowd-management': typeof AppCrowdManagementRoute
  '/dashboard': typeof AppDashboardRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/live-feeds': typeof AppLiveFeedsRouteWithChildren
  '/users': typeof AppUsersRoute
  '/work-monitoring': typeof AppWorkMonitoringRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/live-feeds/$id': typeof AppLiveFeedsIdRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/cameras': typeof AppCamerasRoute
  '/_app/crowd-management': typeof AppCrowdManagementRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/incidents': typeof AppIncidentsRouteWithChildren
  '/_app/live-feeds': typeof AppLiveFeedsRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/_app/work-monitoring': typeof AppWorkMonitoringRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/incidents/$id': typeof AppIncidentsIdRoute
  '/_app/live-feeds/$id': typeof AppLiveFeedsIdRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/alerts'
    | '/analytics'
    | '/audit-logs'
    | '/cameras'
    | '/crowd-management'
    | '/dashboard'
    | '/incidents'
    | '/live-feeds'
    | '/users'
    | '/work-monitoring'
    | '/admin/roles'
    | '/admin/settings'
    | '/incidents/$id'
    | '/live-feeds/$id'
    | '/settings/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/alerts'
    | '/analytics'
    | '/audit-logs'
    | '/cameras'
    | '/crowd-management'
    | '/dashboard'
    | '/incidents'
    | '/live-feeds'
    | '/users'
    | '/work-monitoring'
    | '/admin/roles'
    | '/admin/settings'
    | '/incidents/$id'
    | '/live-feeds/$id'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/alerts'
    | '/_app/analytics'
    | '/_app/audit-logs'
    | '/_app/cameras'
    | '/_app/crowd-management'
    | '/_app/dashboard'
    | '/_app/incidents'
    | '/_app/live-feeds'
    | '/_app/users'
    | '/_app/work-monitoring'
    | '/_app/admin/roles'
    | '/_app/admin/settings'
    | '/_app/incidents/$id'
    | '/_app/live-feeds/$id'
    | '/_app/settings/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/work-monitoring': {
      id: '/_app/work-monitoring'
      path: '/work-monitoring'
      fullPath: '/work-monitoring'
      preLoaderRoute: typeof AppWorkMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live-feeds': {
      id: '/_app/live-feeds'
      path: '/live-feeds'
      fullPath: '/live-feeds'
      preLoaderRoute: typeof AppLiveFeedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crowd-management': {
      id: '/_app/crowd-management'
      path: '/crowd-management'
      fullPath: '/crowd-management'
      preLoaderRoute: typeof AppCrowdManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cameras': {
      id: '/_app/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof AppCamerasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live-feeds/$id': {
      id: '/_app/live-feeds/$id'
      path: '/$id'
      fullPath: '/live-feeds/$id'
      preLoaderRoute: typeof AppLiveFeedsIdRouteImport
      parentRoute: typeof AppLiveFeedsRoute
    }
    '/_app/incidents/$id': {
      id: '/_app/incidents/$id'
      path: '/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AppIncidentsIdRouteImport
      parentRoute: typeof AppIncidentsRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppIncidentsRouteChildren {
  AppIncidentsIdRoute: typeof AppIncidentsIdRoute
}

const AppIncidentsRouteChildren: AppIncidentsRouteChildren = {
  AppIncidentsIdRoute: AppIncidentsIdRoute,
}

const AppIncidentsRouteWithChildren = AppIncidentsRoute._addFileChildren(
  AppIncidentsRouteChildren,
)

interface AppLiveFeedsRouteChildren {
  AppLiveFeedsIdRoute: typeof AppLiveFeedsIdRoute
}

const AppLiveFeedsRouteChildren: AppLiveFeedsRouteChildren = {
  AppLiveFeedsIdRoute: AppLiveFeedsIdRoute,
}

const AppLiveFeedsRouteWithChildren = AppLiveFeedsRoute._addFileChildren(
  AppLiveFeedsRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppCamerasRoute: typeof AppCamerasRoute
  AppCrowdManagementRoute: typeof AppCrowdManagementRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIncidentsRoute: typeof AppIncidentsRouteWithChildren
  AppLiveFeedsRoute: typeof AppLiveFeedsRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppWorkMonitoringRoute: typeof AppWorkMonitoringRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppCamerasRoute: AppCamerasRoute,
  AppCrowdManagementRoute: AppCrowdManagementRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIncidentsRoute: AppIncidentsRouteWithChildren,
  AppLiveFeedsRoute: AppLiveFeedsRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppWorkMonitoringRoute: AppWorkMonitoringRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
